on: 
  push:
    branches: [master]
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get assignment name"
        shell: bash -l {0}
        run: |
          echo "ASSIGNMENT=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 | cut -d- -f1)" >> $GITHUB_ENV;
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Fetch environment file
        shell: bash -l {0}
        run: |
          curl \
          --header 'Authorization: token ${{secrets.PGE311_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE311/${ASSIGNMENT}-solution/contents/environment.yml"
      - name: Fetch Tests 
        shell: bash -l {0}
        run: |
          curl \
          --header 'Authorization: token ${{secrets.PGE311_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE311/${ASSIGNMENT}-solution/contents/test.py"
      - name: Fetch data
        shell: bash -l {0}
        run: |
          cd datasets;
          curl \
          --header 'Authorization: token ${{secrets.PGE311_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE311/${ASSIGNMENT}-solution/contents/datasets/eog_wells_in_nd.csv" \
          -O --location "https://api.github.com/repos/PGE311/${ASSIGNMENT}-solution/contents/datasets/nd_production.csv"
      - name: Fetch gold files
        shell: bash -l {0}
        run: |
          cd images;
          curl \
          --header 'Authorization: token ${{secrets.PGE311_SECRET_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3.raw' \
          -O --location "https://api.github.com/repos/PGE311/${ASSIGNMENT}-solution/contents/images/eog_{oil,gas}_wells_in_nd_gold.png"
      - uses:  mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
      - name: Run Tests 
        shell: bash -l {0}
        run: python -m unittest test.py -vvv
